version: "3.7"

services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    command: npm run start:prod
